name: EC2 Deployment Pipeline

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
#  notify:
#    name: 'Notify Discord'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send workflow URL to Discord
#        run: |
#          curl -H "Content-Type: application/json" \
#          -d '{"content": "A new deployment has been initiated! Approve it here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
#          ${{ secrets.DISCORD_WEBHOOK_URL }}

#  terraform_plan:
#    name: 'Terraform plan'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Init Terraform
#        run: terraform init
#      - name: Validate_Terraform
#        run: terraform validate
#      - name: Plan_Terraform
#        run: terraform plan

  terraform_deploy:
    name: 'Terraform deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: scolley31

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::284482750046:role/gihubaction-terraform
          aws-region: ap-northeast-1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event.action == 'closed'
        run: terraform apply -auto-approve -input=false