name: 'push CI'

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform check'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: src

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::284482750046:role/gihubaction-terraform
          aws-region: ap-northeast-1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

